# Generated by Django 3.2.4 on 2021-07-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('idAutor', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id autor')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre autor')),
                ('historia', models.TextField(verbose_name='Historia')),
                ('img' , models.CharField(max_length=250,verbose_name="path_img"))
            ],
        ),
    ]
