# Generated by Django 3.2.4 on 2021-07-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_autor_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='img',
            field=models.ImageField(max_length=255, upload_to='autores'),
        ),
    ]
