# Generated by Django 3.2.4 on 2021-07-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_autor_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='img',
            field=models.ImageField(null=True, upload_to='autores'),
        ),
    ]
