# Generated by Django 3.2.4 on 2021-07-10 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_autor_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('idObra', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id obra')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre obra')),
                ('historia', models.TextField(verbose_name='Historia')),
                ('img', models.ImageField(null=True, upload_to='obras img')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.autor')),
            ],
        ),
    ]
