# Generated by Django 3.2.4 on 2021-07-10 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_obra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obra',
            old_name='autor',
            new_name='idAutor',
        ),
    ]
