# Generated by Django 3.2.4 on 2021-07-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_autor_obra_idautor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='img',
            field=models.ImageField(null=True, upload_to='obras'),
        ),
    ]
